import type { BusinessConfig, UpgradeConfig, ManagerConfig, PrestigeConfig } from '../types';

export const TICK_RATE = 100; // ms
export const MAX_OFFLINE_HOURS = 12;
export const SAVE_VERSION = 1;

export const PRESTIGE_CONFIG: PrestigeConfig = {
  k: 150,
  alpha: 0.7,
  minEarnings: '1e6', // 1 million
  incomeMultiplier: 1.1, // 10% per level
  speedMultiplier: 0.99, // 1% faster per level
};

export const BUSINESSES: BusinessConfig[] = [
  {
    id: 'lemonade',
    name: 'Lemonade Stand',
    description: 'Your humble beginning',
    icon: '🍋',
    baseCost: '4',
    costGrowth: 1.07,
    baseIncome: '1',
    baseTime: 0.6,
    unlockAt: { type: 'start' },
    order: 1,
  },
  {
    id: 'newspaper',
    name: 'Newspaper Delivery',
    description: 'Deliver the daily news',
    icon: '📰',
    baseCost: '60',
    costGrowth: 1.15,
    baseIncome: '20',
    baseTime: 3,
    unlockAt: { type: 'money', amount: '60' },
    order: 2,
  },
  {
    id: 'carwash',
    name: 'Car Wash',
    description: 'Make cars sparkle',
    icon: '🚗',
    baseCost: '720',
    costGrowth: 1.14,
    baseIncome: '90',
    baseTime: 6,
    unlockAt: { type: 'business', businessId: 'newspaper', level: 1 },
    order: 3,
  },
  {
    id: 'pizza',
    name: 'Pizza Delivery',
    description: 'Hot and fresh',
    icon: '🍕',
    baseCost: '8640',
    costGrowth: 1.13,
    baseIncome: '360',
    baseTime: 12,
    unlockAt: { type: 'business', businessId: 'carwash', level: 1 },
    order: 4,
  },
  {
    id: 'donut',
    name: 'Donut Shop',
    description: 'Sweet profits',
    icon: '🍩',
    baseCost: '103680',
    costGrowth: 1.12,
    baseIncome: '1800',
    baseTime: 24,
    unlockAt: { type: 'business', businessId: 'pizza', level: 1 },
    order: 5,
  },
  {
    id: 'shrimp',
    name: 'Shrimp Boat',
    description: 'Cast your nets wide',
    icon: '🦐',
    baseCost: '1244160',
    costGrowth: 1.11,
    baseIncome: '8640',
    baseTime: 48,
    unlockAt: { type: 'business', businessId: 'donut', level: 1 },
    order: 6,
  },
  {
    id: 'hockey',
    name: 'Hockey Team',
    description: 'Score big profits',
    icon: '🏒',
    baseCost: '14929920',
    costGrowth: 1.10,
    baseIncome: '51840',
    baseTime: 96,
    unlockAt: { type: 'business', businessId: 'shrimp', level: 1 },
    order: 7,
  },
  {
    id: 'studio',
    name: 'Movie Studio',
    description: 'Blockbuster earnings',
    icon: '🎬',
    baseCost: '179159040',
    costGrowth: 1.09,
    baseIncome: '311040',
    baseTime: 192,
    unlockAt: { type: 'business', businessId: 'hockey', level: 1 },
    order: 8,
  },
];

export const MANAGERS: ManagerConfig[] = [
  {
    id: 'lemonade_manager',
    name: 'Cabe Johnson',
    description: 'Runs your lemonade stand',
    businessId: 'lemonade',
    cost: '1000',
    requires: { businessLevel: 25 },
    order: 1,
  },
  {
    id: 'newspaper_manager',
    name: 'Perry Black',
    description: 'Manages newspaper routes',
    businessId: 'newspaper',
    cost: '15000',
    requires: { businessLevel: 50 },
    order: 2,
  },
  {
    id: 'carwash_manager',
    name: 'W. W. Heisenbird',
    description: 'Keeps the car wash running',
    businessId: 'carwash',
    cost: '100000',
    requires: { businessLevel: 100 },
    order: 3,
  },
  {
    id: 'pizza_manager',
    name: 'Mama Mulah',
    description: 'Delivers pizza on time',
    businessId: 'pizza',
    cost: '500000',
    requires: { businessLevel: 100 },
    order: 4,
  },
  {
    id: 'donut_manager',
    name: 'The Dough Boy',
    description: 'Makes donuts round the clock',
    businessId: 'donut',
    cost: '2000000',
    requires: { businessLevel: 100 },
    order: 5,
  },
  {
    id: 'shrimp_manager',
    name: 'Forest Gumpshrimp',
    description: 'Catches shrimp efficiently',
    businessId: 'shrimp',
    cost: '10000000',
    requires: { businessLevel: 100 },
    order: 6,
  },
  {
    id: 'hockey_manager',
    name: 'Dawn Chompsky',
    description: 'Coaches the team to victory',
    businessId: 'hockey',
    cost: '50000000',
    requires: { businessLevel: 100 },
    order: 7,
  },
  {
    id: 'studio_manager',
    name: 'Stefani Speilburger',
    description: 'Produces hit movies',
    businessId: 'studio',
    cost: '250000000',
    requires: { businessLevel: 100 },
    order: 8,
  },
];

export const UPGRADES: UpgradeConfig[] = [
  // Business-specific upgrades
  {
    id: 'lemonade_2x',
    name: 'Fresh Lemons',
    description: 'Double lemonade stand profits',
    cost: '250',
    effects: [{ type: 'business_income', businessId: 'lemonade', multiplier: 2 }],
    requires: { type: 'business', businessId: 'lemonade', level: 25 },
    category: 'business',
    order: 1,
  },
  {
    id: 'lemonade_4x',
    name: 'Organic Lemons',
    description: 'Quadruple lemonade stand profits',
    cost: '10000',
    effects: [{ type: 'business_income', businessId: 'lemonade', multiplier: 4 }],
    requires: { type: 'business', businessId: 'lemonade', level: 50 },
    category: 'business',
    order: 2,
  },
  {
    id: 'newspaper_2x',
    name: 'Color Print',
    description: 'Double newspaper profits',
    cost: '5000',
    effects: [{ type: 'business_income', businessId: 'newspaper', multiplier: 2 }],
    requires: { type: 'business', businessId: 'newspaper', level: 25 },
    category: 'business',
    order: 3,
  },
  {
    id: 'newspaper_4x',
    name: 'Digital Edition',
    description: 'Quadruple newspaper profits',
    cost: '250000',
    effects: [{ type: 'business_income', businessId: 'newspaper', multiplier: 4 }],
    requires: { type: 'business', businessId: 'newspaper', level: 50 },
    category: 'business',
    order: 4,
  },
  
  // Global upgrades
  {
    id: 'global_2x',
    name: 'Business Suit',
    description: 'Double all profits',
    cost: '100000',
    effects: [{ type: 'all_income', multiplier: 2 }],
    requires: { type: 'money', amount: '50000' },
    category: 'global',
    order: 100,
  },
  {
    id: 'global_speed',
    name: 'Time Management',
    description: 'All businesses run 20% faster',
    cost: '1000000',
    effects: [{ type: 'all_speed', multiplier: 0.8 }],
    requires: { type: 'money', amount: '500000' },
    category: 'global',
    order: 101,
  },
  
  // Continue with more upgrades for other businesses...
];