name: CI (Swift)
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with: { swift-version: '6.0' }
      - name: Resolve & test
        run: |
          swift package resolve
          swift test --parallel